name: workflow step

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Cd a directorio
        uses: actions/checkout@v4

      - name: HOLAMUNDO
        run: echo "holamundo"

  second_job:
    runs-on: ubuntu-latest
    if: true
    needs: first_job

    steps:
      - name: instalar dependencias
        run: echo "instalando dependencias..."