name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -name: Repositorio Checkout
        uses: actions/checkout@v3

      -name: Configurar nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'